### PR TITLE
Leverage obmd http server setup code.

### PR DESCRIPTION
**Pull request by zenhack**
Built atop #16. See also the commit message for 606f07e.

Until https://github.com/CCI-MOC/obmd/pull/38 is merged, you'll need to have hil-vpn and that branch of my obmd checked out next to one another (so that the ../obmd path is correct).

### CODE REVIEW

**Comment by zenhack** [comment]
Note that the build failure is because of the aformentioned obmd pr having not been merged yet; I consider this ready to review.

**Review by ianballou — COMMENTED** [review]
I'll give a +1 when the CI passes

**Comment by zenhack** [comment]
I rebased on top of master. This should still fail because the obmd pr still isn't merged, but once it is we should be able to just hit retry.

**Review by naved001 — APPROVED** [review]

**Comment by zenhack** [comment]
I kicked it, should work.

**Comment by zenhack** [comment]
Also removed the replace directive, which isn't needed anymore.

**Comment by zenhack** [comment]
Passed. @ianballou, just waiting on your +2.

**Review by ianballou — APPROVED** [review]

**Pull request merged**
