### PR TITLE
Make various paths configurable at build time.

### PR DESCRIPTION
**Pull request by zenhack**
See #19 and the comments in the Makefile.

### CODE REVIEW

**Review by ianballou — COMMENTED** [review]
This looks fine to me, I'll +1 when Travis passes.  The issue looks like it's just package related so I'm guessing it won't take any major changes to fix

**Comment by zenhack** [comment]
Yeah, it builds fine locally, I'm not sure what the issue is. I rebased now that the other prs are merged, I'll stare at the build errors a bit more.

**Comment by zenhack** [comment]
Fixed, see the last commit.

**Review by ianballou — APPROVED** [review]
Awesome

**Review by naved001 — APPROVED** [review]

**Pull request merged**
